"""JSON schemas for messages flowing through the multi-robot planning pipeline.

Pipeline:
    Offer
      ↓
    Local Plan
      ↓
    Auction
      ↓
    Graph Reasoning
      ↓
    Joint Plan

Local-plan step types:
    LOCAL     : perform an action locally
    ASK_HELP  : ask another robot to perform a task
    HELP      : perform a task requested by another robot
    RECEIVE   : receive a physical item from another robot
    PASS      : pass a physical item to another robot

Pairing semantics:
    ASK_HELP ↔ HELP
    RECEIVE  ↔ PASS
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# basic types
# ---------------------------------------------------------------------------

StepType = Literal[
    "LOCAL",
    "ASK_HELP",
    "HELP",
    "RECEIVE",
    "PASS",
]

Kind = Literal["item", "task"]


# ---------------------------------------------------------------------------
# input
# ---------------------------------------------------------------------------

class AgentInput(BaseModel):
    """Private input available only to one robot."""

    task: str
    capability: str
    images: list[str] = Field(default_factory=list)
    hidden_info: list[str] = Field(default_factory=list)


class TaskConfig(BaseModel):
    """Shared task + private information for each robot."""

    task: str
    agents: list[dict]

    def agent_inputs(self) -> dict[str, AgentInput]:
        return {
            f"agent_{i}": AgentInput(
                task=self.task,
                **a,
            )
            for i, a in enumerate(self.agents, start=1)
        }


# ---------------------------------------------------------------------------
# offer
# ---------------------------------------------------------------------------

class ObsItem(BaseModel):
    """Object or entity observed by the robot."""

    object: str
    location: Optional[str] = None
    state: Optional[str] = None


class CanDoAction(BaseModel):
    """Concrete action the robot can physically perform."""

    action: str
    object: Optional[str] = None
    location: Optional[str] = None
    target: Optional[str] = None


class CannotDoAction(BaseModel):
    """Task-relevant action the robot cannot perform."""

    action: str
    object: Optional[str] = None
    location: Optional[str] = None
    reason: Optional[str] = None


class CanProvide(BaseModel):
    """Physical resource or task capability that can be offered."""

    type: Kind

    # Used mainly for item-level provision.
    object: Optional[str] = None
    location: Optional[str] = None

    # Used mainly for task-level capability.
    action: Optional[str] = None


class OfferNeed(BaseModel):
    """A dependency required by the robot.

    kind="item":
        The robot needs a physical item from another robot.

    kind="task":
        The robot needs another robot to perform a task.
    """

    kind: Kind
    action: Optional[str] = None
    object: Optional[str] = None
    location: Optional[str] = None


class RawOffer(BaseModel):
    """Offer generated by the LLM."""

    capability: str

    obs_scope: list[ObsItem] = Field(
        default_factory=list
    )

    can_do: list[CanDoAction] = Field(
        default_factory=list
    )

    cannot_do: list[CannotDoAction] = Field(
        default_factory=list
    )

    can_provide: list[CanProvide] = Field(
        default_factory=list
    )

    needs: list[OfferNeed] = Field(
        default_factory=list
    )


class Offer(RawOffer):
    """Broadcast Offer with the robot ID attached."""

    agent: str


# ---------------------------------------------------------------------------
# local plan
# ---------------------------------------------------------------------------

class RawStep(BaseModel):
    """One local-plan step generated by the LLM."""

    type: StepType

    # Natural-language description of the step.
    action: str = Field(min_length=1)

    # Optional semantic information.
    # We keep this field because it is useful to distinguish
    # task-level and item-level collaboration in Auction.
    kind: Optional[Kind] = None

    # Physical object involved in RECEIVE / PASS.
    item: Optional[str] = None

    # Non-binding hint about the expected collaborating robot.
    target: Optional[str] = None

    @model_validator(mode="after")
    def _check_step_fields(self):
        # ---------------------------------------------------------------
        # LOCAL
        # ---------------------------------------------------------------
        if self.type == "LOCAL":
            self.kind = None
            self.item = None
            self.target = None
            return self

        # ---------------------------------------------------------------
        # ASK_HELP / HELP
        # ---------------------------------------------------------------
        if self.type in {"ASK_HELP", "HELP"}:
            # These always represent task-level collaboration.
            if self.kind is None:
                self.kind = "task"

            if self.kind != "task":
                raise ValueError(
                    f"{self.type} must use kind='task': {self.action!r}"
                )

            # No physical item is needed for task-level help.
            self.item = None

            return self

        # ---------------------------------------------------------------
        # RECEIVE / PASS
        # ---------------------------------------------------------------
        if self.type in {"RECEIVE", "PASS"}:
            # These always represent physical-item transfer.
            if self.kind is None:
                self.kind = "item"

            if self.kind != "item":
                raise ValueError(
                    f"{self.type} must use kind='item': {self.action!r}"
                )

            if not self.item:
                raise ValueError(
                    f"{self.type} requires 'item': {self.action!r}"
                )

            return self

        return self


class RawLocalPlan(BaseModel):
    """LLM-generated local plan.

    Empty plans are allowed when the robot has no relevant contribution.
    """

    steps: list[RawStep] = Field(
        default_factory=list
    )


class Step(RawStep):
    """Validated local-plan step with code-assigned ID and order."""

    id: str
    order: int


class LocalPlan(BaseModel):
    """A robot's complete local plan."""

    agent: str
    steps: list[Step]

    @classmethod
    def from_raw(
        cls,
        agent: str,
        raw: RawLocalPlan,
        known_agents: set[str],
    ) -> "LocalPlan":

        num = agent.split("_")[-1]

        steps: list[Step] = []

        for i, s in enumerate(raw.steps, start=1):
            data = s.model_dump()

            # target is only a hint.
            # Remove invalid/self references.
            if data["target"] is not None:
                if (
                    data["target"] not in known_agents
                    or data["target"] == agent
                ):
                    data["target"] = None

            steps.append(
                Step(
                    id=f"{num}-{i}",
                    order=i,
                    **data,
                )
            )

        return cls(
            agent=agent,
            steps=steps,
        )

    def collaboration_steps(self) -> list[Step]:
        """Return all non-local collaboration steps."""

        return [
            s
            for s in self.steps
            if s.type != "LOCAL"
        ]

    def ask_help_steps(self) -> list[Step]:
        return [
            s
            for s in self.steps
            if s.type == "ASK_HELP"
        ]

    def help_steps(self) -> list[Step]:
        return [
            s
            for s in self.steps
            if s.type == "HELP"
        ]

    def receive_steps(self) -> list[Step]:
        return [
            s
            for s in self.steps
            if s.type == "RECEIVE"
        ]

    def pass_steps(self) -> list[Step]:
        return [
            s
            for s in self.steps
            if s.type == "PASS"
        ]


# ---------------------------------------------------------------------------
# utilities
# ---------------------------------------------------------------------------

def agent_of(step_id: str) -> str:
    """Convert '3-2' -> 'agent_3'."""
    return f"agent_{step_id.split('-')[0]}"


def describe_config(config: TaskConfig) -> str:
    """Human-readable description of the actual experiment configuration."""

    lines = [
        f"TASK: {config.task}",
        "",
    ]

    for i, a in enumerate(config.agents, start=1):
        lines.append(f"agent_{i}")
        lines.append(
            f"  capability : {a.get('capability', '')}"
        )
        lines.append(
            f"  images     : {a.get('images', [])}"
        )

        hidden = a.get("hidden_info", [])

        lines.append(
            f"  hidden_info: "
            f"{hidden if hidden else '(none)'}"
        )

    return "\n".join(lines)
