# schemas.py

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


StepType = Literal["LOCAL", "NEED", "PASS"]
Kind = Literal["item", "task"]


# ---------------------------------------------------------------------------
# input
# ---------------------------------------------------------------------------

class AgentInput(BaseModel):
    """What one robot receives.
    
    Private inputs never leave the agent.
    Only Offer / Plan are broadcast.
    """

    task: str
    capability: str
    images: list[str] = Field(default_factory=list)
    hidden_info: list[str] = Field(default_factory=list)


class TaskConfig(BaseModel):
    """One scenario: shared task + one entry per robot."""

    task: str
    agents: list[dict]

    def agent_inputs(self) -> dict[str, AgentInput]:
        return {
            f"agent_{i}": AgentInput(task=self.task, **a)
            for i, a in enumerate(self.agents, start=1)
        }


# ---------------------------------------------------------------------------
# offer
# ---------------------------------------------------------------------------

class ObsItem(BaseModel):
    """A concrete object/fact within the robot's observation scope."""

    object: str
    location: Optional[str] = None
    state: Optional[str] = None


class CanDoAction(BaseModel):
    """A concrete action the robot can perform."""

    action: str
    object: Optional[str] = None
    location: Optional[str] = None
    target: Optional[str] = None


class CannotDoAction(BaseModel):
    """A task-relevant action the robot cannot perform."""

    action: str
    object: Optional[str] = None
    location: Optional[str] = None
    reason: Optional[str] = None


class CanProvide(BaseModel):
    """A concrete resource or contribution the robot can provide."""

    type: Kind
    object: Optional[str] = None
    location: Optional[str] = None
    action: Optional[str] = None


class OfferNeed(BaseModel):
    """A concrete dependency required from another robot."""

    kind: Kind
    action: Optional[str] = None
    object: Optional[str] = None
    location: Optional[str] = None


class RawOffer(BaseModel):
    """Structured Offer generated by the LLM."""

    capability: str

    obs_scope: list[ObsItem] = Field(
        default_factory=list
    )

    can_do: list[CanDoAction] = Field(
        default_factory=list
    )

    cannot_do: list[CannotDoAction] = Field(
        default_factory=list
    )

    can_provide: list[CanProvide] = Field(
        default_factory=list
    )

    needs: list[OfferNeed] = Field(
        default_factory=list
    )


class Offer(RawOffer):
    """Broadcast Offer. Agent ID is added by the code."""

    agent: str


# ---------------------------------------------------------------------------
# local plan
# ---------------------------------------------------------------------------

class RawStep(BaseModel):
    """One step as the LLM writes it."""

    type: StepType
    action: str = Field(min_length=1)

    kind: Optional[Kind] = None
    item: Optional[str] = None
    target: Optional[str] = None

    @model_validator(mode="after")
    def _check_collab_fields(self):
        if self.type == "LOCAL":
            self.kind = self.item = self.target = None
            return self

        if self.kind is None:
            raise ValueError(
                f"{self.type} step needs 'kind' (item|task): {self.action!r}"
            )

        if self.kind == "item" and not self.item:
            raise ValueError(
                f"{self.type}/item step needs 'item': {self.action!r}"
            )

        return self


class RawLocalPlan(BaseModel):
    steps: list[RawStep] = Field(default_factory=list)


class Step(RawStep):
    id: str
    order: int


class LocalPlan(BaseModel):
    agent: str
    steps: list[Step]

    @classmethod
    def from_raw(
        cls,
        agent: str,
        raw: RawLocalPlan,
        known_agents: set[str],
    ) -> "LocalPlan":

        num = agent.split("_")[-1]

        steps: list[Step] = []

        for i, s in enumerate(raw.steps, start=1):
            data = s.model_dump()

            # target is only a hint
            if (
                data["target"] is not None
                and (
                    data["target"] not in known_agents
                    or data["target"] == agent
                )
            ):
                data["target"] = None

            steps.append(
                Step(
                    id=f"{num}-{i}",
                    order=i,
                    **data,
                )
            )

        return cls(
            agent=agent,
            steps=steps,
        )

    def collaboration_steps(self) -> list[Step]:
        return [
            s for s in self.steps
            if s.type != "LOCAL"
        ]


def agent_of(step_id: str) -> str:
    """'3-2' -> 'agent_3'"""

    return f"agent_{step_id.split('-')[0]}"
