# schemas.py

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


StepType = Literal["LOCAL", "NEED", "PASS"]
Kind = Literal["item", "task"]


# ===========================================================================
# INPUT
# ===========================================================================

class AgentInput(BaseModel):
    """
    Private input received by one robot.

    Raw images and hidden information remain private.
    Only Offer / Local Plan are broadcast.
    """

    task: str
    capability: str
    images: list[str] = Field(default_factory=list)
    hidden_info: list[str] = Field(default_factory=list)


class TaskConfig(BaseModel):
    """One scenario: shared task + one entry per robot."""

    task: str
    agents: list[dict]

    def agent_inputs(self) -> dict[str, AgentInput]:
        return {
            f"agent_{i}": AgentInput(
                task=self.task,
                **agent,
            )
            for i, agent in enumerate(self.agents, start=1)
        }


def describe_config(config: TaskConfig) -> str:
    """Create a human-readable summary of the configuration."""

    lines = [
        f"TASK: {config.task}",
        "",
        f"NUMBER OF AGENTS: {len(config.agents)}",
    ]

    for i, agent in enumerate(config.agents, start=1):
        lines.append("")
        lines.append(f"AGENT {i}")
        lines.append(
            f"  CAPABILITY: {agent.get('capability', '')}"
        )
        lines.append(
            f"  IMAGES: {len(agent.get('images', []))}"
        )
        lines.append(
            f"  HIDDEN INFO: {len(agent.get('hidden_info', []))} items"
        )

    return "\n".join(lines)


# ===========================================================================
# OFFER
# ===========================================================================

class ObsItem(BaseModel):
    """
    Concrete object/fact within the robot's observation scope.
    """

    object: str
    location: Optional[str] = None
    state: Optional[str] = None


class CanDoAction(BaseModel):
    """
    Concrete action the robot can perform itself.
    """

    action: str
    object: Optional[str] = None
    location: Optional[str] = None
    target: Optional[str] = None


class CannotDoAction(BaseModel):
    """
    Task-relevant action that the robot cannot perform.
    """

    action: str
    object: Optional[str] = None
    location: Optional[str] = None
    reason: Optional[str] = None


class CanProvide(BaseModel):
    """
    Concrete resource or contribution that the robot can provide.
    """

    type: Kind
    object: Optional[str] = None
    location: Optional[str] = None
    action: Optional[str] = None


class OfferNeed(BaseModel):
    """
    Concrete dependency required from another robot.

    `kind == "item"`:
        The robot needs a physical item.

    `kind == "task"`:
        The robot needs another robot to perform an action/task.
    """

    kind: Kind
    action: Optional[str] = None
    object: Optional[str] = None
    location: Optional[str] = None


class RawOffer(BaseModel):
    """
    Structured Offer generated by the LLM.

    The LLM does not generate the robot ID.
    """

    capability: str

    obs_scope: list[ObsItem] = Field(
        default_factory=list
    )

    can_do: list[CanDoAction] = Field(
        default_factory=list
    )

    cannot_do: list[CannotDoAction] = Field(
        default_factory=list
    )

    can_provide: list[CanProvide] = Field(
        default_factory=list
    )

    needs: list[OfferNeed] = Field(
        default_factory=list
    )


class Offer(RawOffer):
    """
    Broadcast Offer.

    Agent ID is added by the runtime code.
    """

    agent: str


# ===========================================================================
# LOCAL PLAN
# ===========================================================================

class RawStep(BaseModel):
    """
    One local-plan step generated by the LLM.
    """

    type: StepType

    action: str = Field(
        min_length=1
    )

    kind: Optional[Kind] = None
    item: Optional[str] = None
    target: Optional[str] = None

    @model_validator(mode="after")
    def _check_collab_fields(self):

        # LOCAL does not need collaboration metadata.
        if self.type == "LOCAL":
            self.kind = None
            self.item = None
            self.target = None
            return self

        # NEED / PASS must specify whether the collaboration
        # concerns an item or a task.
        if self.kind is None:
            raise ValueError(
                f"{self.type} step needs 'kind' "
                f"(item|task): {self.action!r}"
            )

        # Item collaboration must identify the item.
        if self.kind == "item" and not self.item:
            raise ValueError(
                f"{self.type}/item step needs 'item': "
                f"{self.action!r}"
            )

        return self


class RawLocalPlan(BaseModel):
    """
    Raw local plan generated by the LLM.

    Empty plans are allowed because a robot may have
    no relevant contribution to the global task.
    """

    steps: list[RawStep] = Field(
        default_factory=list
    )


class Step(RawStep):
    """
    Validated local-plan step with deterministic ID/order.
    """

    id: str
    order: int


class LocalPlan(BaseModel):
    agent: str
    steps: list[Step]

    @classmethod
    def from_raw(
        cls,
        agent: str,
        raw: RawLocalPlan,
        known_agents: set[str],
    ) -> "LocalPlan":

        num = agent.split("_")[-1]

        steps: list[Step] = []

        for i, s in enumerate(raw.steps, start=1):

            data = s.model_dump()

            # target is only a preferred coordination hint.
            # Invalid/self targets are removed.
            if (
                data["target"] is not None
                and (
                    data["target"] not in known_agents
                    or data["target"] == agent
                )
            ):
                data["target"] = None

            steps.append(
                Step(
                    id=f"{num}-{i}",
                    order=i,
                    **data,
                )
            )

        return cls(
            agent=agent,
            steps=steps,
        )

    def collaboration_steps(self) -> list[Step]:
        return [
            s
            for s in self.steps
            if s.type != "LOCAL"
        ]


def agent_of(step_id: str) -> str:
    """
    '3-2' -> 'agent_3'
    """

    return f"agent_{step_id.split('-')[0]}"
